services:
  postgres:
    image: postgres:15.5
    container_name: signature-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
      TZ: Asia/Tokyo
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: signature-redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3.0
    container_name: signature-localstack
    environment:
      - DEBUG=1
      - SERVICES=s3,lambda,sns,sqs,kms,secretsmanager
      - AWS_DEFAULT_REGION=ap-northeast-1
      - PERSISTENCE=1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  # Lambda開発用 (SAM Local)
  lambda-dev:
    image: public.ecr.aws/sam/build-nodejs18.x:latest
    container_name: signature-lambda-dev
    working_dir: /app
    volumes:
      - ./src/lambda:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
    command: sam local start-api --host 0.0.0.0 --port 3001

volumes:
  postgres:
    driver: local
  localstack_data:
    driver: local